version: '3.9'

networks:
  p3o:
    external: true

services:
  postgres:
    container_name: postgres
    image: docker.iranserver.com/postgres:17
    env_file:
      - ./.env
    volumes:
      - postgres_p3o_data:/var/lib/postgresql/data
    networks:
      - p3o
    ports:
      - "5432:5432"
    restart: always

  redis:
    container_name: redis
    image: docker.iranserver.com/bitnami/redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
    env_file:
      - ./.env
    volumes:
      - redis_p3o_data:/var/lib/redis
    networks:
      - p3o
    ports:
      - "6379:6379"
    restart: always

  p3o:
    container_name: p3o
    image: docker.iranserver.com/gatec/p3o:${VERSION}
    env_file:
      - ./.env
    networks:
      - p3o
    ports:
      - "7765:7765"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_p3o_data:
  redis_p3o_data:
