service_name: "chipmunk"
version: "v2.1.2"
grpc_port: 10101
amqp_configs:
  connection: "amqp://rabbitmq:rabbitmq@rabbitmq"
buffer_configs:
  candle_buffer_length: 400
markets_app:
  service_configs:
    network_address: "network:10101"
    eagle_address: "eagle:10101"
    core_address: "core:10101"
  worker_configs:
    core_address: "core:10101"
    market_statistics_worker_interval: "5ms"
candles_app:
  service_configs:
    core_address: "core:10101"
    eagle_address: ":eagle:10101"
  worker_configs:
    core_address: "core:10101"
    primary_data_queue: "chipmunk_ohlc"
    consumer_count: 10
    missed_candles_interval: "10m"
    last_candles_interval: "3s"
    redundant_remover_interval: "15m"
indicators_app:
  service_configs:
resolutions_app:
  service_configs:
wallets_app:
  service_configs:
    core_address: "core:10101"
  buffer_configs:
  worker_configs:
    core_address: "core:10101"
    wallet_worker_interval: "10s"
gormConfigs:
  type: "postgreSQL"
  username: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5432
  name: "p3o"
  is_ssl_enable: false